/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 14-nov.-2022 20:01:37 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 

DROP DATABASE IF EXISTS `codigo_azul`
;

CREATE DATABASE `codigo_azul`
;

USE `codigo_azul`
;

/* Drop Tables */

DROP TABLE IF EXISTS `alarmas` CASCADE
;

DROP TABLE IF EXISTS `enfermeros` CASCADE
;

DROP TABLE IF EXISTS `pacientes` CASCADE
;

DROP TABLE IF EXISTS `registros` CASCADE
;

DROP TABLE IF EXISTS `ubicaciones` CASCADE
;

DROP TABLE IF EXISTS `usuarios` CASCADE
;

/* Create Tables */

CREATE TABLE `alarmas`
(
	`ID_Alarma` INT NOT NULL AUTO_INCREMENT,
	`Descripcion` VARCHAR(50) NOT NULL,
	`ID_Ubicacion` INT NOT NULL,
	`Origen` VARCHAR(50) NOT NULL,
	`Estado` BOOL NOT NULL DEFAULT 1,
	`Creado` DATETIME NULL DEFAULT current_timestamp(),
	`Editado` DATETIME NULL DEFAULT current_timestamp(),
	CONSTRAINT `PK_alarmas` PRIMARY KEY (`ID_Alarma` ASC)
)

;

CREATE TABLE `enfermeros`
(
	`ID_Enfermero` INT NOT NULL AUTO_INCREMENT,
	`Nombre` VARCHAR(50) NOT NULL,
	`Apellido` VARCHAR(50) NOT NULL,
	`DNI` INT NOT NULL,
	`Estado` VARCHAR(50) NOT NULL DEFAULT 1,
	`Creado` DATETIME NULL DEFAULT current_timestamp(),
	`Editado` DATETIME NULL DEFAULT current_timestamp(),
	CONSTRAINT `PK_enfermeros` PRIMARY KEY (`ID_Enfermero` ASC)
)

;

CREATE TABLE `pacientes`
(
	`ID_Paciente` INT NOT NULL AUTO_INCREMENT,
	`Nombre` VARCHAR(50) NOT NULL,
	`Apellido` VARCHAR(50) NOT NULL,
	`DNI` INT NOT NULL,
	`Telefono` VARCHAR(30) NOT NULL,
	`Direccion` VARCHAR(50) NOT NULL,
	`Localidad` VARCHAR(50) NOT NULL,
	`Provincia` VARCHAR(50) NOT NULL,
	`Obra_Social` VARCHAR(50) NOT NULL,
	`NroObraSocial` INT NULL,
	`Medico_Cabecera` VARCHAR(50) NOT NULL,
	`Padecimiento` TEXT NOT NULL,
	`GrupoSanguineo` VARCHAR(5) NOT NULL,
	`ID_Enfermero` INT NOT NULL,
	`ID_Ubicacion` INT NOT NULL,
	`Estado` BOOL NOT NULL DEFAULT 1,
	`Creado` DATETIME NULL DEFAULT current_timestamp(),
	`Editado` DATETIME NULL DEFAULT current_timestamp(),
	CONSTRAINT `PK_pacientes` PRIMARY KEY (`ID_Paciente` ASC)
)

;

CREATE TABLE `registros`
(
	`ID_Registro` INT NOT NULL AUTO_INCREMENT,
	`ID_Alarma` INT NOT NULL,
	`FechaHora` DATETIME NOT NULL DEFAULT current_timestamp(),
	`Tipo` VARCHAR(50) NOT NULL,
	`Atentido` BOOL NOT NULL DEFAULT 0,
	`FechaHoraAtendido` DATETIME NULL,
	CONSTRAINT `PK_registro` PRIMARY KEY (`ID_Registro` ASC)
)

;

CREATE TABLE `ubicaciones`
(
	`ID_Ubicacion` INT NOT NULL AUTO_INCREMENT,
	`Piso` INT NOT NULL,
	`Area` VARCHAR(50) NOT NULL,
	`Sala` VARCHAR(50) NULL,
	`Estado` BOOL NOT NULL DEFAULT 1,
	`Creado` DATETIME NULL DEFAULT current_timestamp(),
	`Editado` DATETIME NULL DEFAULT current_timestamp(),
	CONSTRAINT `PK_areas` PRIMARY KEY (`ID_Ubicacion` ASC)
)

;

CREATE TABLE `usuarios`
(
	`ID_Usuario` INT NOT NULL AUTO_INCREMENT,
	`NombreCompleto` VARCHAR(60) NOT NULL,
	`Usuario` VARCHAR(20) NOT NULL,
	`Password` VARCHAR(256) NOT NULL,
	`Rol` VARCHAR(20) NOT NULL,
	`Estado` BOOL NOT NULL DEFAULT 1,
	`Creado` DATETIME NULL DEFAULT current_timestamp(),
	`Editado` DATETIME NULL DEFAULT current_timestamp(),
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Usuario` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `alarmas` 
 ADD CONSTRAINT `FK_alarmas_ubicacion`
	FOREIGN KEY (`ID_Ubicacion`) REFERENCES `ubicaciones` (`ID_Ubicacion`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pacientes` 
 ADD CONSTRAINT `FK_pacientes_enfermeros`
	FOREIGN KEY (`ID_Enfermero`) REFERENCES `enfermeros` (`ID_Enfermero`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pacientes` 
 ADD CONSTRAINT `FK_pacientes_ubicacion`
	FOREIGN KEY (`ID_Ubicacion`) REFERENCES `ubicaciones` (`ID_Ubicacion`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `registros` 
 ADD CONSTRAINT `FK_registro_alarmas`
	FOREIGN KEY (`ID_Alarma`) REFERENCES `alarmas` (`ID_Alarma`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 

INSERT INTO `ubicaciones` (`ID_Ubicacion`, `Piso`, `Area`, `Sala`, `Estado`, `Creado`, `Editado`) VALUES
(1, 1, 'Quirofano', '1', 1, '2022-11-14 19:37:41', '2022-11-14 19:37:41'),
(2, 1, 'Terapia Intensiva', '5', 1, '2022-11-14 19:38:18', '2022-11-14 19:38:18');

INSERT INTO `alarmas` (`ID_Alarma`, `Descripcion`, `ID_Ubicacion`, `Origen`, `Estado`, `Craedo`, `Editado`) VALUES
(1, 'Alarma 32', 1, 'Baño', 1, '2022-11-14 19:42:58', '2022-11-14 19:42:58');

INSERT INTO `enfermeros` (`ID_Enfermero`, `Nombre`, `Apellido`, `DNI`, `Estado`, `Creado`, `Editado`) VALUES
(1, 'Thiago Mariano', 'Lance', 11111111, '1', '2022-11-14 19:41:14', '2022-11-14 19:41:14');

INSERT INTO `pacientes` (`ID_Paciente`, `Nombre`, `Apellido`, `DNI`, `Telefono`, `Direccion`, `Localidad`, `Provincia`, `Obra_Social`, `NroObraSocial`, `Medico_Cabecera`, `Padecimiento`, `GrupoSanguineo`, `ID_Enfermero`, `ID_Ubicacion`, `Estado`, `Creado`, `Editado`) VALUES
(1, 'Gerónimo', 'Di Battista', 11111111, '+549123412345', 'Rivadavia 1212', 'Saladillo', 'Buenos Aires', 'IOMA', 11111111, '-', '-', 'A+', 1, 1, 1, '2022-11-14 19:41:37', '2022-11-14 19:41:37');